### ISSUE TITLE
Checking orientation of density planes with respect to Skysim5000 galaxies

### ISSUE THREAD

**Issue by nvanalfen** [LSSTDESC/SkySim5000_IA_infusion#12]
Comparing Skysim galaxies (read in between redshift ranges corresponding to files in z2ts_HACCY1_106.txt) with the corresponding file from z2ts_HACCY1_106.txt.

to load the healpix map, we used:

```python
# Convert (ra, dec) to HEALPix pixel indices
pix_indices = hp.ang2pix(nside, np.pi/2 + dec_rad, ra_rad)

# Create an empty HEALPix map
healpix_map = np.zeros(hp.nside2npix(nside), dtype=int)

# Bin the galaxy coordinates into the HEALPix map
for idx in pix_indices:
    healpix_map[idx] += 1
```

Below are shown the mass map (top) from density_map_323_dens.bin, and the galaxy population (bottom) from Skysim5000 limited to the same redshfit range indicated for map_323 in z2ts_HACCY1_106.txt.

![image](https://user-images.githubusercontent.com/26467203/226565399-68a89ad5-857d-4155-bb57-aa3f06e8c6de.png)

![image](https://user-images.githubusercontent.com/26467203/226565498-bef33c02-d5e5-4fd0-a9cb-4b2581536c38.png)

**Comment by nvanalfen** [comment]
Galaxy populations do seem to align with mass densities. However, the files (e.g. map_323 in z2ts_HACCY1_106.txt) on their own seem to hold more redshifts than what's listed in z2ts_HACCY1_106.txt.

When comparing mass sheets, the densities in map_323 matched (reasonably) with the galaxy populations in Skysim5000 when I read the redshift range used for map_328 and map_323 (the redshift bin immediately below the one read in, and the redshift bin read in). In other words, we needed the redshift bin listed and the prior redshift bin (See images below).

The first image shows the mass sheet from map_323.

The second image shows the galaxy populations in skysim in the redshift range for map_328 and map_323 combined.

![image](https://user-images.githubusercontent.com/26467203/226627873-384861a1-ff92-473a-86be-14a4cd9a608e.png)

![image](https://user-images.githubusercontent.com/26467203/226627952-4e3aaf60-3c4f-478c-a2f1-c17e0aa651ef.png)

Is this expected?

**Comment by jharno** [comment]
There are many redshift files in that directory. You need to use the one called z2ts.txt, not z2ts_HACCY1_[19,50,106].txt. These are for another set of DESC simulations. Can you retry with the correct file?

**Comment by jharno** [comment]
Do you happen to know of a notebook where you do the galaxy assignment to healpix grids? I am producing a new lensing catalogue from the exact same mass shells, but this time it is designed to match exactly the TATT model (@EiffL might have communicate this with you) and I need to do this same comparison.

**Comment by nvanalfen** [comment]
ok, we looked at z2ts.txt and that told us we (well, at least I) might be doing something wrong. For the redshifts in the file you mentioned, will the ranges be halfway between the two snapshots? e.g. if I have three snapshots at 0, 0.1, and 0.2, would the middle snapshot range from 0.05 to 0.15?

I can upload the notebook I'm using for this, if that's allowed. Can I also upload the saved ra, dec, and redshift values? I stored these in a .npy file so I don't have to keep loading the Skysim catalog over and over since it takes such a long time.

I'm not familiar with the organizational structure of where to store data and notebooks for repos like this.

**Comment by jharno** [comment]
I have added you as a contributor to this github, which means you have now write permission. Can you try to upload the notebook?

**Comment by nvanalfen** [comment]
Uploaded. It's the notebook called check_skysim_footprint.ipynb. I did not upload the .npy files holding the ra, dec, and redshift for the regions I cared about as they are each several hundred megabytes. Loading the relevant regions takes a while, but I can send the files by other means if you want them

**Comment by jharno** [comment]
That's perfect, many thanks! 
Any updates on the agreement between mass and HOD-galaxies?

**Comment by nvanalfen** [comment]
So looking at the images above, it does look like the galaxy populations in skysim seem to agree with the denser regions in the redshift range we looked at. There are certainly features in the mass density that I don't see in the galaxy population image, but it looks like the densest regions show more galaxies. I haven't done anything with generating HOD models for it.

**Comment by jharno** [comment]
Are you selecting all the galaxies falling in the redshift range that defines the underlying mass map?

**Comment by nvanalfen** [comment]
yes. I'm grabbing ra and dec (and redshift) for all galaxies in the catalog within that redshift range. (I'm also grabbing redshift so I can look at subsections as well).

**Comment by jharno** [comment]
Great! That means that these two maps (HOD gal & matter) can be cross-correlated to measure the galaxy bias and correlation lengths ( InverseFourrier(P_gm/sqrt(P_gg*P_mm)), for instance, Great work! Would it be a good place to close this issue now, since it appears you've completed the task, or was there something else you wanted to do?

**Comment by nvanalfen** [comment]
I think it's a good place to close it. I'll go ahead and do that with this comment. Thanks!
