### ISSUE TITLE
Measuring C_ell with NaMaster

### ISSUE THREAD

**Issue by jharno** [LSSTDESC/SkySim5000_IA_infusion#2]
NaMaster might help us in dealing with the fact that SkySim5000 only covers an octant, while the angular power spectrum is computed over the full sky, introducing oscillatory features on large scales when the footprint is ignored. A mask file can be found here: /global/homes/j/jharno/IA-infusion/SkySim5000/FullSky_weight.fits. This is a Healpix map, with NSIDE=8192, in which pixels are set to 1.0 in the Octant and 0.0 elsewhere.

**Comment by jharno** [comment]
Hi @EiffL, could you push a notebook where this NaMaster measurement is done and where this plot can be reproduced?

**Comment by EiffL** [comment]
@dlanzieri can you update the notebook? The namaster code was already correct in the current notebook, I had just the wrong cosmological parameters in my theory computation.

**Comment by dlanzieri** [comment]
@EiffL @jharno it's already updated, I pushed the correct version of the notebook last Friday
